name: Build and Deploy Service Feature Branch

run-name: "${{ inputs.SERVICE_NAME }}_${{ inputs.CLIENT }}_deploy"

###
# Workflow to Build and Deploy a Service Feature Branch
###

on:
  workflow_dispatch:
    inputs:
      #   RUNNER_LABEL:
      #     type: string
      #     required: false
      #     description: "Runner label to run the workflow on"
      #     default: "ubuntu-latest"
      ENV:
        type: string
        required: false
        default: "qa"
        description: "Environment to deploy to"
      CLIENT:
        type: string
        required: false
        default: "lifebit_internal"
        description: "Client to deploy to"

# Environment variables
env:
  VERSION: $GITHUB_REF
  APP: $GITHUB_REPOSITORY
  RUNNER_LABEL: "ubuntu-latest"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ${{ inputs.RUNNER_LABEL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Print vars
        run: |
          echo "APP: ${{ inputs.APP }}"
          echo "VERSION: ${{ inputs.VERSION }}"
          echo "AWS_CREDENTIALS_FILE_NAME: ${{ inputs.AWS_CREDENTIALS_FILE_NAME }}"
          echo "PRODUCT_FILE: ${{ inputs.PRODUCT_FILE }}"
          echo "DEPLOYMENT_FILE: ${{ inputs.DEPLOYMENT_FILE }}"
          echo "ENV: ${{ inputs.ENV }}"
          echo "CLIENT: ${{ inputs.CLIENT }}"
