run-name: "${{ inputs.CLIENT }}_${{ inputs.ENV }}_deploy"

###
# Workflow to Build and Deploy a Service Feature Branch
###

on:
  workflow_call:
    inputs:
      RUNNER_LABEL:
        type: string
        required: false
        description: "Runner label to run the workflow on"
        default: "ubuntu-latest"
      APP:
        type: string
        required: false
        description: "App name to deploy"
        default: $GITHUB_REPOSITORY
      VERSION:
        type: string
        required: false
        description: "App version to deploy"
        default: $GITHUB_REF
      ENV:
        type: string
        required: true
        description: "Environment to deploy to"
      CLIENT:
        type: string
        required: true
        description: "Client to deploy to"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ${{ inputs.RUNNER_LABEL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Print vars
        run: |
          echo "APP: ${{ inputs.APP }}"
          echo "VERSION: ${{ inputs.VERSION }}"
          echo "ENV: ${{ inputs.ENV }}"
          echo "CLIENT: ${{ inputs.CLIENT }}"
