name: Test PR pipeline

run-name: "${{ github.event.pull_request.title || github.event.head_commit.message || format('Test PR pipeline in {0} {1} by {2}', github.ref_type, github.ref_name, github.actor) }}"

on:

  pull_request:
    branches:
      - "*"


jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: echo "Tests passed"
      
      - name: Comment Pipeline
        run: |
          echo "Security vulnerabilities found in the image" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            # Security vulnerabilities found in the image

